# Generated by Django 2.2.16 on 2020-09-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32, verbose_name='昵称')),
                ('phonenum', models.IntegerField(max_length=11, verbose_name='手机号')),
                ('birthday', models.DateTimeField(default=2018, verbose_name='生日')),
                ('gender', models.BooleanField(default='1', verbose_name='性别')),
                ('location', models.CharField(default='中国', max_length=128, verbose_name='常居地')),
            ],
        ),
    ]
