# Generated by Django 2.2.16 on 2020-09-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(db_index=True, max_length=32, verbose_name='昵称')),
                ('phonenum', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('birthday', models.DateTimeField(default='2002-01-01', verbose_name='生日')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=8, verbose_name='性别')),
                ('location', models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('深圳', '深圳'), ('成都', '成都'), ('西安', '西安'), ('武汉', '武汉'), ('沈阳', '沈阳')], default='北京', max_length=32, verbose_name='常居地')),
                ('avatar', models.CharField(default='q', max_length=256, verbose_name='头像')),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
    ]
