# Generated by Django 2.2.16 on 2020-09-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenum', models.IntegerField(help_text='手机号', max_length=11, unique=True, verbose_name='手机号')),
                ('nickname', models.CharField(help_text='昵称', max_length=32, verbose_name='昵称')),
                ('gender', models.BooleanField(choices=[(1, 'male'), (2, 'female')], default=1, help_text='性别', verbose_name='性别')),
                ('birthday', models.DateField(help_text='生日', verbose_name='生日')),
                ('location', models.CharField(help_text='常居地', max_length=64, verbose_name='常居地')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
    ]
