# Generated by Django 2.2.16 on 2020-09-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phonenum',
            field=models.CharField(help_text='手机号', max_length=11, unique=True, verbose_name='手机号'),
        ),
    ]
