# Generated by Django 2.2.16 on 2020-09-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200922_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='gender',
            field=models.BooleanField(choices=[(1, 'male'), (0, 'female')], default=1, help_text='性别', verbose_name='性别'),
        ),
    ]
