# Generated by Django 2.2.16 on 2020-09-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200922_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='birthday',
            field=models.DateField(default='2020-01-01', help_text='生日', verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='location',
            field=models.CharField(default='上海市宝山区', help_text='常居地', max_length=64, verbose_name='常居地'),
        ),
    ]
