# Generated by Django 2.2.16 on 2020-09-22 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200922_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dating_gender', models.BooleanField(choices=[(1, 'male'), (0, 'female')], default=1, help_text='匹配性别', verbose_name='性别')),
                ('dating_location', models.CharField(default='上海市宝山区', help_text='目标城市', max_length=64, verbose_name='目标城市')),
                ('max_distance', models.FloatField(default=20.0, help_text='最⼤查找范围', verbose_name='最⼤查找范围')),
                ('min_distance', models.FloatField(default=1.0, help_text='最小查找范围', verbose_name='最小查找范围')),
                ('max_dating_age', models.IntegerField(default=40, help_text='最⼤交友年龄', verbose_name='最⼤交友年龄')),
                ('min_dating_age', models.IntegerField(default=20, help_text='最小交友年龄', verbose_name='最小交友年龄')),
                ('vibration', models.BooleanField(choices=[(1, 'open'), (0, 'close')], default=1, help_text='开启震动', verbose_name='开启震动')),
                ('only_matched', models.BooleanField(default=1, help_text='不让未匹配的⼈看我的相册', verbose_name='不让未匹配的⼈看我的相册')),
                ('auto_play', models.BooleanField(default=1, help_text='自动播放视频', verbose_name='自动播放视频')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserModel')),
            ],
            options={
                'verbose_name': '用户配置',
                'verbose_name_plural': '用户配置',
                'db_table': 'userconfig',
            },
        ),
    ]
