# Generated by Django 2.2.16 on 2020-09-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200922_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='dating_gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='male', help_text='匹配性别', max_length=32, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='male', help_text='性别', max_length=16, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='location',
            field=models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('深圳', '深圳'), ('成都', '成都'), ('西安', '西安'), ('武汉', '武汉'), ('沈阳', '沈阳')], default='上海', help_text='常居地', max_length=64, verbose_name='常居地'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='nickname',
            field=models.CharField(db_index=True, help_text='昵称', max_length=32, verbose_name='昵称'),
        ),
    ]
