# Generated by Django 2.2.16 on 2020-09-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200923_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='dating_location',
            field=models.CharField(default='上海市', help_text='目标城市', max_length=64, verbose_name='目标城市'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='vibration',
            field=models.BooleanField(default=1, help_text='开启震动', verbose_name='开启震动'),
        ),
    ]
