# Generated by Django 2.2.16 on 2020-09-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200924_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='avatar',
            field=models.CharField(default='', max_length=256, verbose_name='个人形象'),
        ),
    ]
